# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
 email_provider_username: <%= ENV["upchuks"] %>
 email_provider_password: <%= ENV["WWWolverinee@#$2"] %>
 domain_name: example.com
 mailchimp_api_key: <%= ENV["5f91624848de9d9678ed6462dd016b59-us13"] %>
 mailchimp_list_id: <%= ENV["49e89b92c5"] %>
 owner_email: <%= ENV["upchuks2@gmail.com"] %>
  secret_key_base: f08775232e92c073034bb89c5e4bbcd8353f0c5baa29c55bc1d7697e562f2b58513fc5f2eefe816394e509e1152a696f74e0044b171571f137b81630e05e34b4

test:
  secret_key_base: 0b454fd504faa73cebabfc33cea68b6657def3c6ceb0e1b84d6205e97d2116e37d45ea544950f88d4b353f2e6f718b9b772eaaf4aafa4858f16426cfda05543a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 email_provider_username: <%= ENV["upchuks"] %>
 email_provider_password: <%= ENV["WWWolverinee@#$2"] %>
 domain_name: example.com
 mailchimp_api_key: <%= ENV["5f91624848de9d9678ed6462dd016b59-us13"] %>
 mailchimp_list_id: <%= ENV["49e89b92c5"] %>
 owner_email: <%= ENV["upchuks2@gmail.com"] %>
 secret_key_base: <%= ENV["f08775232e92c073034bb89c5e4bbcd8353f0c5baa29c55bc1d7697e562f2b58513fc5f2eefe816394e509e1152a696f74e0044b171571f137b81630e05e34b4"] %>